# Generated by Django 2.1.1 on 2018-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Hello World'),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default='2018-09-18'),
        ),
    ]
